### ISSUE TITLE
Query Timeout during export results in a RDFParse Exception

### ISSUE THREAD

**Issue by ajithnn** [aws/neptune-export#132]
When AWS Neptune Query Timeout is set to 300 seconds.

```
Creating statement files
[main] INFO com.amazonaws.services.neptune.io.Status - 100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 1900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 2900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 3900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 4900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 5900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 6900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7800000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 7900000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8000000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8100000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8200000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8300000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8400000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8500000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8600000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8700000 (statements)
[main] INFO com.amazonaws.services.neptune.io.Status - 8800000 (statements)

An error occurred while exporting RDF as NTRIPLES. Elapsed time: 301 seconds


An error occurred while exporting rdf graph. Elapsed time: 306 seconds

java.lang.RuntimeException: com.amazonaws.AmazonServiceException:  (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null)
	at com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeGSPExport(NeptuneSparqlClient.java:218)
	at com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeCompleteExport(NeptuneSparqlClient.java:177)
	at com.amazonaws.services.neptune.rdf.ExportRdfGraphJob.lambda$execute$0(ExportRdfGraphJob.java:42)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
	at com.amazonaws.services.neptune.rdf.ExportRdfGraphJob.execute(ExportRdfGraphJob.java:38)
	at com.amazonaws.services.neptune.ExportRdfGraph.lambda$run$0(ExportRdfGraph.java:77)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
	at com.amazonaws.services.neptune.ExportRdfGraph.run(ExportRdfGraph.java:60)
	at com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:72)
	at com.amazonaws.services.neptune.NeptuneExportCli.main(NeptuneExportCli.java:48)
Caused by: com.amazonaws.AmazonServiceException:  (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null)
	at com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeGSPExport(NeptuneSparqlClient.java:208)
	... 11 more
Caused by: org.eclipse.rdf4j.rio.RDFParseException: IRI included an unencoded space:   [line 8873725]
```

**Comment by ajithnn** [comment]
Fix is to increase the timeout to a larger number to ensure the export goes through. The exception itself is unclear and could be more helpful.

**Comment by ksridhar** [comment]
Thank you @ajithnn , specifically the `neptune_query_timeout` cluster parameter.

**Comment by Cole-Greer** [comment]
Thanks for reporting this issue @ajithnn, the timeout errror (as well as any other error message from the server) should be replicated in the client side exception. I will look into why it is missing in this case and work on a fix.

**Comment by Cole-Greer** [comment]
A fix for this bug has been merged and will be included in the next release of Neptune Export.
