### ISSUE TITLE
Handling HTTP trailing headers in response for error messages from Neptune

### ISSUE THREAD

**Issue by xiazcy** [aws/neptune-export#17]
Related to https://github.com/awslabs/amazon-neptune-tools/issues/127.

It appears that Neptune inserts error messages in the middle of response body, which causes corrupt responses and `unknown record` or `malformed query` exceptions from the RDF4j library when it tries to parse the response. 

As advised in Neptune docs, https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-sparql-http-trailing-headers.html, we'll need to add a TE header in our request and investigate how to parse the custom response headers for error, either on Neptune Export side (custom HTTP client?) or the RDF4J library side (adding API support for parsing custom response headers?).

**Comment by Cole-Greer** [comment]
Fixed in PR #18. Sample output during a timeout exception now looks like this:
```
Creating statement files

An error occurred while exporting RDF as Turtle. Elapsed time: 0 seconds


An error occurred while exporting rdf graph. Elapsed time: 1 seconds

java.lang.RuntimeException: X-Neptune-Status: 500 TimeLimitExceededException
X-Neptune-Detail: {"code":"TimeLimitExceededException","requestId":"dcc37392-6714-4e18-e301-efab45ec6ea2","detailedMessage":"Operation terminated (deadline exceeded)"}

        at com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeTupleQuery(NeptuneSparqlClient.java:125)
        at com.amazonaws.services.neptune.rdf.ExportRdfGraphJob.lambda$execute$0(ExportRdfGraphJob.java:34)
        at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
        at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
        at com.amazonaws.services.neptune.rdf.ExportRdfGraphJob.execute(ExportRdfGraphJob.java:31)
        at com.amazonaws.services.neptune.ExportRdfGraph.lambda$run$0(ExportRdfGraph.java:77)
        at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
        at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
        at com.amazonaws.services.neptune.ExportRdfGraph.run(ExportRdfGraph.java:60)
        at com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:72)
        at com.amazonaws.services.neptune.NeptuneExportCli.main(NeptuneExportCli.java:48)
Caused by: org.eclipse.rdf4j.query.QueryEvaluationException: Unkown record type: 123
        at org.eclipse.rdf4j.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:59)
        at com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeTupleQuery(NeptuneSparqlClient.java:121)
        ... 10 more
Caused by: java.io.IOException: Unkown record type: 123
        at org.eclipse.rdf4j.query.resultio.binary.BinaryQueryResultParser.parse(BinaryQueryResultParser.java:188)
        at org.eclipse.rdf4j.query.resultio.AbstractTupleQueryResultParser.parseQueryResult(AbstractTupleQueryResultParser.java:48)
        at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getTupleQueryResult(SPARQLProtocolSession.java:699)
        at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQuery(SPARQLProtocolSession.java:369)
        at org.eclipse.rdf4j.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:56)
        ... 11 more
An error occurred while exporting from Neptune: X-Neptune-Status: 500 TimeLimitExceededException
X-Neptune-Detail: {"code":"TimeLimitExceededException","requestId":"dcc37392-6714-4e18-e301-efab45ec6ea2","detailedMessage":"Operation terminated (deadline exceeded)"}
```
